import { useEffect, useRef, useState } from "react";
import { getIntelligence, saveIntelligence } from "../lib/intelligence";
import springvaleLogo from "../assets/springvale-city-logo.png";
import "./AIStudio.css";

const processingSteps = [
  "Uploading Match", "Identifying Players", "Tracking Ball Movement", "Calculating Statistics",
  "Detecting Possession", "Generating Heat Maps", "Finding Highlights", "Generating Player Ratings",
  "Updating Player Development", "Updating Match Library", "Updating Football Intelligence",
  "Preparing Session Builder", "Preparing Equipment List", "Creating AI Summary",
];

export default function AIStudio({ isOpen = true, embedded = false, role, user, onClose = () => {}, onNavigate }) {
  const [file, setFile] = useState(null);
  const [status, setStatus] = useState("ready");
  const [progress, setProgress] = useState(0);
  const [activeStep, setActiveStep] = useState(-1);
  const [playerId, setPlayerId] = useState("ava");
  const timers = useRef([]);

  useEffect(() => {
    if (!isOpen) return undefined;
    let selected = role === "player" ? user?.playerProfile?.id : user?.linkedChildren?.[0]?.id;
    try { selected = localStorage.getItem("matchvisionActivePlayerId") || selected; } catch { /* Use account context. */ }
    setPlayerId(selected || "ava");
    return () => { timers.current.forEach(clearTimeout); timers.current = []; };
  }, [isOpen, role, user]);

  useEffect(() => {
    if (!isOpen || embedded) return undefined;
    const closeOnEscape = (event) => { if (event.key === "Escape") onClose(); };
    document.body.classList.add("ai-studio-open");
    window.addEventListener("keydown", closeOnEscape);
    return () => { document.body.classList.remove("ai-studio-open"); window.removeEventListener("keydown", closeOnEscape); };
  }, [embedded, isOpen, onClose]);

  if (!isOpen) return null;

  const playerName = role === "player" ? user?.name : user?.linkedChildren?.find((child) => child.id === playerId)?.name || "Ava Thompson";
  const roleLabel = role === "coach" ? "Team Match" : role === "admin" ? "Club Match" : role === "parent" ? `${playerName}'s Match` : "My Match";
  const uploadCopy = role === "parent"
    ? ["Upload Child's Match", "Upload a video of your child's match and MatchVision AI will automatically analyse their performance, generate highlights and update their development."]
    : role === "player"
      ? ["Upload My Match", "Upload your latest match to receive AI statistics, highlights and development insights."]
      : role === "admin"
        ? ["Upload Club Match", "Analyse any club match to generate player, team and club intelligence."]
        : ["Upload Team Match", "Upload a team match to unlock player statistics, tactical analysis, opponent intelligence and coaching recommendations."];
  let recentAnalyses = [];
  try { recentAnalyses = JSON.parse(localStorage.getItem("matchvisionAIStudioMatches") || "[]"); } catch { /* Show the connected demo record. */ }
  if (!recentAnalyses.length) recentAnalyses = [{ id: "connected-demo", title: "Springvale vs Oakleigh", date: "Latest connected match", status: "AI complete", highlights: 11 }];

  function completeAnalysis() {
    const previous = getIntelligence();
    const completedAt = new Date().toISOString();
    const connected = saveIntelligence({
      ...previous,
      sourceFile: file?.name || "Springvale_Mobile_Match_Recording.mp4",
      completedAt,
      match: { ...previous.match, score: "3-2", venue: "Ross Reserve", pitch: "Pitch 1" },
      player: { ...previous.player, id: playerId, name: playerName, rating: "8.7", progress: Math.min(100, previous.player.progress + 3) },
    });
    const generatedMatch = { id: `studio-${Date.now()}`, title: "Springvale 3-2 Oakleigh", date: "Analysed just now", status: "AI complete", visibility: role === "parent" || role === "player" ? "Approved personal replay" : "Club coaching staff", highlights: 11, approved: true, playerIds: [playerId] };
    try {
      const matches = JSON.parse(localStorage.getItem("matchvisionAIStudioMatches") || "[]");
      localStorage.setItem("matchvisionAIStudioMatches", JSON.stringify([generatedMatch, ...matches]));
      localStorage.setItem("matchvisionRecommendedSession", JSON.stringify({ title: connected.recommendedSession.title, trainingFocus: connected.findings.priority, objective: "Improve defensive transitions", duration: connected.recommendedSession.duration, coachNotes: "Generated by AI Studio from the latest match.", selectedDrills: connected.recommendedSession.drills, equipment: connected.equipment, sourceMatch: generatedMatch.title }));
    } catch { /* Connected demo remains available in memory. */ }
    setStatus("complete");
    setProgress(100);
  }

  function beginAnalysis() {
    timers.current.forEach(clearTimeout);
    timers.current = [];
    setStatus("processing"); setProgress(2); setActiveStep(0);
    processingSteps.forEach((_, index) => {
      const timer = window.setTimeout(() => {
        setActiveStep(index);
        setProgress(Math.round(((index + 1) / processingSteps.length) * 96));
        if (index === processingSteps.length - 1) {
          const completionTimer = window.setTimeout(completeAnalysis, 450);
          timers.current.push(completionTimer);
        }
      }, 460 * (index + 1));
      timers.current.push(timer);
    });
  }

  const openResult = (target) => { onClose(); onNavigate(target); };

  return <div className={embedded ? "ai-studio-destination" : "ai-studio-backdrop"} role={embedded ? undefined : "dialog"} aria-modal={embedded ? undefined : "true"} aria-label="MatchVision AI Studio" onClick={() => !embedded && status !== "processing" && onClose()}>
    <section className="ai-studio" onClick={(event) => event.stopPropagation()}>
      <header><div className="ai-studio-brand"><img src={springvaleLogo} alt="" /><div><span>MATCHVISION</span><strong>AI STUDIO</strong><small>Upload and analyse matches.</small></div></div>{!embedded && <button type="button" aria-label="Close AI Studio" disabled={status === "processing"} onClick={onClose}>X</button>}</header>
      {status === "ready" && <><div className="ai-studio-ready"><div className="ai-studio-story"><span>AI COMMAND CENTRE</span><h1>{uploadCopy[0]}</h1><p>{uploadCopy[1]}</p><div className="ai-studio-context"><strong>{roleLabel}</strong><small>{role === "coach" || role === "admin" ? "Full tactical and operational analysis" : "Private personal development analysis"}</small></div></div><div className="ai-studio-upload"><label><input type="file" accept="video/*" hidden onChange={(event) => setFile(event.target.files?.[0] || null)} /><i>UPLOAD</i><strong>{file?.name || "Choose match recording"}</strong><span>MP4, MOV or approved phone video</span></label>{role === "parent" && user?.linkedChildren?.length > 1 && <label className="ai-studio-player"><span>Linked child</span><select value={playerId} onChange={(event) => { setPlayerId(event.target.value); try { localStorage.setItem("matchvisionActivePlayerId", event.target.value); } catch { /* Keep selection in memory. */ } }}>{user.linkedChildren.map((child) => <option value={child.id} key={child.id}>{child.name} - {child.team}</option>)}</select></label>}<button type="button" className="ai-studio-primary" onClick={beginAnalysis}>{file ? uploadCopy[0] : "Use Demo Recording"}</button><button type="button" onClick={() => { setStatus("complete"); setProgress(100); }}>Continue Previous Analysis</button></div></div><section className="ai-studio-command-grid"><article><span>RECENT ANALYSES / RECENT UPLOADS</span><h2>Analysis history & completed reports</h2>{recentAnalyses.slice(0,3).map((match) => <button type="button" key={match.id} onClick={() => openResult(role === "parent" ? "child-analysis" : "analysis")}><strong>{match.title}</strong><small>{match.date} - {match.status}</small></button>)}</article><article><span>RECENT HIGHLIGHTS / AI DISCOVERIES</span><h2>Everything updates from here</h2><div><button type="button" onClick={() => openResult("matches")}>Match Library</button><button type="button" onClick={() => openResult(role === "parent" ? "child-analysis" : "analysis")}>AI Reports</button><button type="button" onClick={() => openResult("highlights")}>Recent Highlights</button><button type="button" onClick={() => openResult(role === "parent" || role === "player" ? "player-development" : role === "admin" ? "club-pulse" : "football-intelligence")}>AI Discoveries</button></div></article><article><span>PROCESSING QUEUE</span><h2>No matches waiting</h2><p>Your next upload will appear here while MatchVision detects players, builds statistics and updates connected tools.</p><b>READY FOR UPLOAD</b></article></section></>}
      {status === "processing" && <div className="ai-studio-processing"><div className="ai-studio-progress"><span>AI PROCESSING - {progress}%</span><h2>MatchVision is building your football intelligence.</h2><div><i style={{ width: `${progress}%` }} /></div><small>{processingSteps[activeStep]}</small></div><div className="ai-studio-timeline">{processingSteps.map((step,index) => <article className={index < activeStep ? "complete" : index === activeStep ? "active" : ""} key={step}><i>{index < activeStep ? "OK" : index === activeStep ? "AI" : String(index+1).padStart(2,"0")}</i><span>{step}</span><b>{index < activeStep ? "Complete" : index === activeStep ? "Working..." : "Queued"}</b></article>)}</div></div>}
      {status === "complete" && <div className="ai-studio-complete"><div className="ai-studio-complete-mark">OK</div><span>AI STUDIO COMPLETE</span><h1>One upload updated the entire platform.</h1><p>Your role-safe results are already available. Open any result below - there is nothing else to configure.</p><div className="ai-studio-result-grid"><button type="button" onClick={() => openResult("matches")}><strong>Match Library</strong><span>New match record created</span></button><button type="button" onClick={() => openResult(role === "parent" ? "child-analysis" : "analysis")}><strong>AI Analysis</strong><span>{role === "parent" || role === "player" ? "Personal review ready" : "Full report ready"}</span></button><button type="button" onClick={() => openResult("highlights")}><strong>Highlights</strong><span>11 key moments detected</span></button><button type="button" onClick={() => openResult(role === "parent" || role === "player" ? "player-development" : role === "admin" ? "club-pulse" : "football-intelligence")}><strong>{role === "parent" || role === "player" ? "Development" : role === "admin" ? "Club Intelligence" : "Football Intelligence"}</strong><span>Connected insight updated</span></button>{role === "coach" && <button type="button" onClick={() => openResult("session-builder")}><strong>Session Builder</strong><span>Recommended session prepared</span></button>}</div><button type="button" className="ai-studio-primary" onClick={() => openResult(role === "parent" ? "child-analysis" : role === "player" ? "analysis" : role === "admin" ? "club-pulse" : "football-intelligence")}>Open Recommended Next Step</button></div>}
    </section>
  </div>;
}
