import { useState } from "react";
import { demoPlayerProfiles } from "../data/playerProfile";
import { getRecognitionRecords } from "../data/recognition";
import "./MatchIntelligenceReport.css";
import "./MatchIntelligenceArchive.css";

const squad = [
  { id: "james", name: "James Smith", number: 9, position: "Striker", initials: "JS", rating: 8.9, minutes: 60, first: 30, second: 30, bench: 0, on: "Started", off: "Full time", goals: 2, assists: 0, trend: "+0.7" },
  { id: "ava", name: "Ava Thompson", number: 10, position: "Attacking Midfielder", initials: "AT", rating: 8.7, minutes: 52, first: 30, second: 22, bench: 8, on: "Started", off: "52'", goals: 1, assists: 1, trend: "+0.5" },
  { id: "lucas", name: "Lucas Brown", number: 4, position: "Centre Back", initials: "LB", rating: 8.2, minutes: 60, first: 30, second: 30, bench: 0, on: "Started", off: "Full time", goals: 0, assists: 0, trend: "+0.3" },
  { id: "emily", name: "Emily Jones", number: 7, position: "Right Wing", initials: "EJ", rating: 8.4, minutes: 45, first: 30, second: 15, bench: 15, on: "Started", off: "45'", goals: 0, assists: 1, trend: "+0.6" },
  { id: "noah", name: "Noah Wilson", number: 6, position: "Central Midfielder", initials: "NW", rating: 7.9, minutes: 38, first: 8, second: 30, bench: 22, on: "22'", off: "Full time", goals: 0, assists: 0, trend: "+0.2" },
];

const teamStats = [["Possession", "57%"], ["Pass accuracy", "78%"], ["Shots", "8"], ["On target", "5"], ["Recoveries", "41"], ["Final-third entries", "24"]];
const detailStats = [["Shots", "4"], ["Shot accuracy", "75%"], ["Touches", "52"], ["Passes", "38"], ["Pass accuracy", "82%"], ["Forward passes", "19"], ["Progressive passes", "11"], ["Crosses", "4"], ["Key passes", "3"], ["Successful dribbles", "5"], ["Tackles", "4"], ["Interceptions", "3"], ["Recoveries", "7"], ["Duels won", "8/11"], ["Distance covered", "5.4 km"], ["Sprint count", "17"], ["Maximum speed", "Coming soon"], ["Possession time", "4m 18s"], ["Ball involvement", "High"], ["Influence rating", "86%"]];

function PlayerReport({ player, personal = false, role }) {
  const playingPercentage = Math.round((player.minutes / 60) * 100);
  const recognition = getRecognitionRecords().find((item) => item.playerId === player.id);
  return <article className="mir-player-report">
    <header><div className="mir-avatar">{player.initials}</div><div><span>{personal ? (role === "parent" ? "LINKED CHILD" : "MY MATCH") : `#${player.number} · ${player.position}`}</span><h3>{player.name}</h3><p>AI match rating <strong>{player.rating}</strong> <b>↗ {player.trend}</b></p></div><div className="mir-rating"><strong>{player.rating}</strong><span>AI RATING</span></div></header>
    <section className="mir-playing-time"><div><strong>{player.minutes}</strong><span>Total minutes</span></div><div><strong>{player.first}</strong><span>First half</span></div><div><strong>{player.second}</strong><span>Second half</span></div><div><strong>{player.bench}</strong><span>Bench time</span></div><div><strong>{player.on}</strong><span>Substituted on</span></div><div><strong>{player.off}</strong><span>Substituted off</span></div><div><strong>10 min</strong><span>Break duration</span></div><div><strong>{playingPercentage}%</strong><span>Playing percentage</span></div><div><strong>{playingPercentage > 80 ? "Excellent" : "Strong"}</strong><span>Participation</span></div></section>
    <div className="mir-player-detail"><div className="mir-stat-matrix">{[["Goals", player.goals], ["Assists", player.assists], ...detailStats].map(([label, value]) => <div key={label}><span>{label}</span><strong>{label === "Maximum speed" ? "—" : value}</strong><small>{label === "Maximum speed" ? value : "AI detected"}</small></div>)}</div><div className="mir-heat-panel"><span>PLAYER HEAT MAP</span><div className="mir-heat-map"><i /><i /><i /><i /><b>{player.number}</b></div><small>Highest influence through the right half-space and central transition lane.</small></div></div>
    <section className="mir-development"><article><span>STRENGTHS</span><h4>Progressive movement and work rate</h4><p>Created space, supported transitions and stayed involved in decisive phases.</p></article><article><span>AREA TO IMPROVE</span><h4>First touch under pressure</h4><p>Open body position earlier and scan before receiving in central areas.</p></article><article><span>COACH FEEDBACK</span><h4>Positive, composed contribution</h4><p>Keep scanning before the ball arrives and trust the first forward option.</p></article><article><span>DEVELOPMENT GOAL</span><h4>Three early scans before receiving</h4><p>Track this goal in Player Development during the next two matches.</p></article><article><span>COACH FOCUS · NEXT MATCH</span><h4>Faster decisions after recovery</h4><p>Release the first forward option within three seconds of regaining possession.</p></article></section>
    <footer><div><span>DEVELOPMENT PRIORITY</span><strong>Receiving and transition speed</strong></div><div><span>PREVIOUS MATCH</span><strong>Rating 8.2 · ↗ Improving</strong></div><div><span>AWARDS</span><strong>{recognition?.awardType || "Best On Field candidate"}</strong></div><div><span>CERTIFICATES</span><strong>{recognition ? "Certificate available" : "No new certificate"}</strong></div><div><span>LATEST HIGHLIGHTS</span><strong>{player.goals + player.assists + 2} approved clips</strong></div></footer>
  </article>;
}

export default function MatchIntelligenceReport({ role = "coach", user, compact = false, onNavigate, workspace }) {
  const restricted = role === "parent" || role === "player";
  let linkedId = role === "player" ? user?.playerProfile?.id : user?.linkedChildren?.[0]?.id;
  try { linkedId = localStorage.getItem("matchvisionActivePlayerId") || linkedId; } catch { /* Retain account context. */ }
  const profile = demoPlayerProfiles[linkedId] || demoPlayerProfiles.ava;
  const reportSquad = workspace?.squad?.length ? workspace.squad : squad;
  const personalPlayer = { ...(reportSquad.find((item) => item.id === "ava") || reportSquad[0]), ...reportSquad.find((item) => item.id === profile.id), id: profile.id, name: profile.name, initials: profile.initials, position: profile.position, number: profile.number || 10 };
  const visibleSquad = restricted ? [personalPlayer] : reportSquad;
  const [selectedId, setSelectedId] = useState(visibleSquad[0].id);
  const selected = visibleSquad.find((item) => item.id === selectedId) || visibleSquad[0];
  return <section className={`match-intelligence-report ${compact ? "compact" : ""}`} aria-label="AI match intelligence report">
    <header className="mir-title"><div><span>✦ MATCHVISION AI · CONNECTED REPORT</span><h2>{restricted ? `${selected.name}'s match intelligence` : workspace?.match?.title || (role === "admin" ? "Club match intelligence" : "Springvale U11 match intelligence")}</h2><p>{restricted ? "Only the approved analytics linked to this account are visible." : "One match record connects tactical, team, player, development and operational intelligence."}</p></div><strong>{workspace?.confidence || 94}%<small>AI CONFIDENCE</small></strong></header>
    <nav className="mir-report-order" aria-label="Report sections">{["Summary", "Match Statistics", "Team Statistics", "Heat Maps", "Highlights", "Player Development", "Coach Recommendations", "Squad Analytics", "AI Summary"].map((item, index) => <span key={item}><b>{index + 1}</b>{item}</span>)}</nav>
    <section className="mir-summary"><article><span>AI MATCH SUMMARY</span><h3>{workspace?.match?.title || "Springvale 3–2 Oakleigh"}</h3><p>{workspace?.summary || "Strong right-side progression and improved second-half control created the result. Defensive recovery after left-channel turnovers remains the clearest development priority."}</p></article><div>{(workspace?.teamStats || teamStats).map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>Match detected</small></article>)}</div></section>
    <div className="mir-visual-grid"><article><span>TEAM HEAT MAP</span><h3>Territory and influence</h3><div className="mir-team-heat"><i /><i /><i /></div></article><article><span>HIGHLIGHTS</span><h3>{workspace?.highlights || 11} moments created</h3><div className="mir-highlight-bars"><i style={{width:"88%"}} /><i style={{width:"67%"}} /><i style={{width:"78%"}} /></div><button type="button" onClick={() => onNavigate?.("highlights")}>Open approved highlights →</button></article><article><span>COACH RECOMMENDATION</span><h3>{workspace?.coachRecommendation || "Train defensive transitions"}</h3><p>Use the archived match findings to prepare the next development session.</p><button type="button" onClick={() => onNavigate?.("session-builder")}>Open Session Builder →</button></article></div>
    <section className="mir-squad"><header><div><span>{restricted ? "PERSONAL ANALYTICS" : "SQUAD ANALYTICS"}</span><h2>{restricted ? "Your approved match view" : "Every player. One connected match."}</h2></div>{role === "admin" && <small>Squad comparison · participation review enabled</small>}</header>{!restricted && <div className="mir-player-selector">{visibleSquad.map((player) => <button type="button" className={selected.id === player.id ? "active" : ""} onClick={() => setSelectedId(player.id)} key={player.id}><i>{player.initials}</i><span><strong>{player.name}</strong><small>#{player.number} · {player.position}</small></span><b>{player.rating}</b></button>)}</div>}<PlayerReport player={selected} personal={restricted} role={role} /></section>
    {workspace && <section className="mir-archive-grid"><article><span>FOOTBALL INTELLIGENCE</span><h3>{workspace.footballIntelligence?.priority}</h3><p>Team compactness: {workspace.footballIntelligence?.compactness}. Strength: {workspace.footballIntelligence?.strength}.</p></article><article><span>OPPONENT INTELLIGENCE</span><h3>{workspace.opponentIntelligence?.opponent}</h3><p>{workspace.opponentIntelligence?.threat}. Opportunity: {workspace.opponentIntelligence?.opportunity}.</p></article><article><span>SESSION BUILDER RECOMMENDATION</span><h3>{workspace.sessionBuilder?.title}</h3><p>{workspace.sessionBuilder?.duration} · {(workspace.sessionBuilder?.drills || []).join(" · ")}</p></article><article><span>COACH NOTES</span><h3>Archived with this match</h3><p>{workspace.coachNotes}</p></article><article className="mir-match-timeline"><span>MATCH TIMELINE</span><div>{workspace.timeline?.map(([time, event]) => <div key={`${time}-${event}`}><b>{time}</b><p>{event}</p></div>)}</div></article><article><span>DEVELOPMENT & RECOGNITION</span><h3>{workspace.recognition?.[0]?.award || "Recognition review"}</h3><p>{workspace.recognition?.[0]?.playerName}: {workspace.recognition?.[0]?.reason}. {(workspace.developmentInsights || []).join(" · ")}</p></article></section>}
    <section className="mir-ai-summary"><span>✦ MATCHVISION AI SUMMARY</span><h2>{role === "admin" ? "Participation is strong across this analysed squad." : restricted ? `${selected.name} is progressing with a clear next focus.` : "The squad is improving, with one actionable training priority."}</h2><p>{role === "admin" ? "Minute distribution is balanced, player retention signals remain positive and two high-load players should be monitored before the next fixture." : "Match evidence has updated development, recognition candidates, highlights, Football Intelligence and Session Builder without creating duplicate records."}</p></section>
  </section>;
}
